# Generated by Django 5.1 on 2024-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_country_of_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone_number',
            field=models.TextField(blank=True, max_length=13, null=True),
        ),
    ]
