# Generated by Django 5.1 on 2024-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cellphone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
