services:
  app:
    # image: bigbravedigital/puula:latest
    build:
      context: .
    command: >
      sh -c "/venv/bin/python3 manage.py wait_for_db &&
             /venv/bin/python3 manage.py migrate &&
            /venv/bin/python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ./data/web:/vol/web
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:14.10-alpine
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
