# Generated by Django 5.1 on 2024-09-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_remove_company_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modality', models.CharField(blank=True, choices=[('Balance', 'Balance'), ('Bodybuilding', 'Bodybuilding'), ('Cardio', 'Cardio'), ('Endurance', 'Endurance'), ('Flexibility', 'Flexibility'), ('Functional', 'Functional'), ('High Intensity', 'High Intensity'), ('Hypertrophy', 'Hypertrophy'), ('Mobility', 'Mobility'), ('Power', 'Power'), ('Plyometrics', 'Plyometrics'), ('Strength', 'Strength'), ('Speed', 'Speed'), ('Stability', 'Stability'), ('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Activation', 'Activation'), ('Agility', 'Agility'), ('Other', 'Other')], max_length=100, null=True)),
                ('muscle_group', models.CharField(blank=True, choices=[('Abdominals', 'Abdominals'), ('Adductors', 'Adductors'), ('Biceps', 'Biceps'), ('Calves', 'Calves'), ('Chest', 'Chest'), ('Forearms', 'Forearms'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings'), ('Lats', 'Lats'), ('Lower Back', 'Lower Back'), ('Middle Back', 'Middle Back'), ('Neck', 'Neck'), ('Quadriceps', 'Quadriceps'), ('Shoulders', 'Shoulders'), ('Traps', 'Traps'), ('Triceps', 'Triceps'), ('Other', 'Other')], max_length=100, null=True)),
                ('movement_pattern', models.CharField(blank=True, choices=[('Horizontal Push', 'Horizontal Push'), ('Horizontal Pull', 'Horizontal Pull'), ('Vertical Push', 'Vertical Push'), ('Vertical Pull', 'Vertical Pull'), ('Squat', 'Squat'), ('Hinge', 'Hinge'), ('Lunge', 'Lunge'), ('Twist', 'Twist'), ('Gait', 'Gait'), ('Push', 'Push'), ('Pull', 'Pull'), ('Carry', 'Carry'), ('Other', 'Other')], max_length=100, null=True)),
                ('excercise_category', models.CharField(blank=True, choices=[('Strength', 'Strength'), ('Bodyweight', 'Bodyweight'), ('Timed', 'Timed'), ('Distance (Long)', 'Distance (Long)'), ('Distance (Short)', 'Distance (Short)')], max_length=100, null=True)),
                ('tracking_field', models.CharField(blank=True, choices=[('Reps', 'Reps'), ('Time', 'Time'), ('Distance', 'Distance'), ('Weight', 'Weight'), ('Sets', 'Sets'), ('Rounds', 'Rounds'), ('Calories', 'Calories'), ('Other', 'Other')], max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='exercise_videos/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='exercise_photos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Kettlebell', 'Kettlebell'), ('Medicine Ball', 'Medicine Ball'), ('Resistance Bands', 'Resistance Bands'), ('TRX', 'TRX'), ('Bosu Ball', 'Bosu Ball'), ('Stability Ball', 'Stability Ball'), ('Sandbag', 'Sandbag'), ('Sled', 'Sled'), ('Battle Ropes', 'Battle Ropes'), ('Plyo Box', 'Plyo Box'), ('Foam Roller', 'Foam Roller'), ('Yoga Mat', 'Yoga Mat'), ('Jump Rope', 'Jump Rope'), ('Pull Up Bar', 'Pull Up Bar'), ('Box', 'Box'), ('Bench', 'Bench'), ('Rings', 'Rings'), ('Parallettes', 'Parallettes'), ('Tire', 'Tire'), ('Squat Rack', 'Squat Rack'), ('Peg Board', 'Peg Board'), ('Climbing Rope', 'Climbing Rope'), ('Ski Erg', 'Ski Erg'), ('Rowing Machine', 'Rowing Machine'), ('Air Bike', 'Air Bike'), ('Treadmill', 'Treadmill'), ('Elliptical', 'Elliptical'), ('Stairmaster', 'Stairmaster'), ('Spin Bike', 'Spin Bike'), ('Other', 'Other')], max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='companies.company')),
            ],
        ),
    ]
