# Generated by Django 5.1 on 2024-08-31 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_company', models.CharField(blank=True, choices=[('gym', 'gym'), ('fitness_center', 'fitness_center'), ('yoga_center', 'yoga_center'), ('dance_center', 'dance_center'), ('nutrition_center', 'nutrition_center'), ('physiotherapy_center', 'physiotherapy_center'), ('psychology_center', 'psychology_center'), ('counselling_center', 'counselling_center'), ('life_coaching_center', 'life_coaching_center'), ('career_coaching_center', 'career_coaching_center'), ('business_coaching_center', 'business_coaching_center'), ('academic_coaching_center', 'academic_coaching_center'), ('music_center', 'music_center'), ('art_center', 'art_center'), ('craft_center', 'craft_center'), ('language_center', 'language_center'), ('other', 'other')], max_length=100, null=True)),
                ('number_of_teammates', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=100, null=True)),
                ('number_of_clients', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='brands.brand')),
                ('users', models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
