# Generated by Django 5.1 on 2024-09-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
    ]
